version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - pip install uv
    post_install:
      - uv sync --all-extras
sphinx:
  configuration: source/conf.py
formats: all
